[FEATURE] 버전 관리 기능 추가
Team-TIFY/TIFY-SERVER pull request #116
Opened 2023-11-28 06:51 UTC by bongsh0112

## 📝 PR Summary

앱 버전 기능을 추가합니다

#### 🌲 Working Branch

feat/113-app-version

#### 🌲 TODOs

- 버전 테이블 신규 생성
- 새로운 버전 save usecase
- 버전 조회 usecase

### Related Issues

#113

2023-11-28 14:34 UTC, sanbonai06 commented on Api/src/main/java/tify/server/api/version/model/vo/VersionInfoVo.java
> +    @Schema(description = "AOS 버전입니다.")
혹시 모르니 스키마 설명 바꿔주시면 좋겠어용

2023-11-28 14:35 UTC, sanbonai06 commented on Domain/src/main/java/tify/server/domain/domains/version/domain/Version.java
> +@Setter
setter말고 public 메서드로 업데이트 하는게 더 좋을 것 같아용

2023-11-28 14:36 UTC, sanbonai06 commented on Api/src/main/java/tify/server/api/version/service/CreateVersionUseCase.java
> +        versionAdaptor.save(version);
각각 Optional로 검증하고 version.updateAosVersion으로만 하면 굳이 다시 save할 필요 없을 것 같아용

2023-11-28 14:36 UTC, sanbonai06 requested changes
수정사항 적어놨습니다

2023-11-28 15:14 UTC, bongsh0112 commented on Api/src/main/java/tify/server/api/version/model/vo/VersionInfoVo.java
> +    @Schema(description = "AOS 버전입니다.")
넵

2023-11-28 15:15 UTC, bongsh0112 commented on Api/src/main/java/tify/server/api/version/service/CreateVersionUseCase.java
> +        versionAdaptor.save(version);
이렇게 되면 Version 테이블에는 하나의 레코드만 있고 그걸 계속 변경하는 방식인가요?

2023-11-28 15:15 UTC, bongsh0112 commented on Domain/src/main/java/tify/server/domain/domains/version/domain/Version.java
> +@Setter
확인했습니닷

2023-11-29 05:01 UTC, sanbonai06 commented on Api/src/main/java/tify/server/api/version/service/CreateVersionUseCase.java
> +        versionAdaptor.save(version);
넵 그러면 굳이 limit1로 version entity를 끌어오는게 아니고 항상 하나만 조회 할 수 있기 때문에 더 좋은 것 같아용

2023-11-29 05:06 UTC, bongsh0112 commented on Api/src/main/java/tify/server/api/version/service/CreateVersionUseCase.java
> +        versionAdaptor.save(version);
확인했습니당

2023-11-29 05:24 UTC, sanbonai06 approved these changes

2023-11-29 05:25 UTC, merged