[FEATURE] 특정 데일리 질문에 대한 친구들의 답변 몰아보기 API 작성
Team-TIFY/TIFY-SERVER pull request #118
Opened 2023-11-28 14:35 UTC by bongsh0112

## 📝 PR Summary

특정 데일리 질문에 대한 친구들의 답변 몰아보기 API 작성

#### 🌲 Working Branch

feat/112-neighbor-answer-list

#### 🌲 TODOs

### Related Issues

close #112

2023-11-28 14:43 UTC, sanbonai06 commented on Api/src/main/java/tify/server/api/answer/model/vo/AnswerInfoVo.java
> +    }
이건 혹시 무슨일이 있었던 거죠?? answer가 없는데 조회 할 일이 있나요??

2023-11-28 14:46 UTC, sanbonai06 commented on Api/src/main/java/tify/server/api/answer/service/RetrieveDailyAnswerUseCase.java
> +                        .toList();
neighborList와 friendIdList가 다른게 뭐죠??

2023-11-28 14:46 UTC, sanbonai06 requested changes
이건 내일 아침에 다시 봐야 할 것 같아요
저 위에 것만 먼저 수정해주세용

2023-11-28 15:11 UTC, bongsh0112 commented on Api/src/main/java/tify/server/api/answer/model/vo/AnswerInfoVo.java
> +    }
내 친구들이 특정 데일리 질문에 답변하지 않았을 때 그 친구들은 answer가 null이기 때문입니닷

2023-11-28 15:12 UTC, bongsh0112 commented on Api/src/main/java/tify/server/api/answer/service/RetrieveDailyAnswerUseCase.java
> +                        .toList();
neighborList는 User 객체 list고 friendIdList는 User pk list입니다
둘 중에 하나를 지울 수 있을 것 같기도 하네요...?!?!

2023-11-29 05:01 UTC, sanbonai06 commented on Api/src/main/java/tify/server/api/answer/model/vo/AnswerInfoVo.java
> +    }
👍

2023-11-29 05:02 UTC, sanbonai06 commented on Api/src/main/java/tify/server/api/answer/service/RetrieveDailyAnswerUseCase.java
> +                .toList();
속이 뻥

2023-11-29 05:02 UTC, sanbonai06 approved these changes

2023-11-29 05:03 UTC, bongsh0112 commented on Api/src/main/java/tify/server/api/answer/service/RetrieveDailyAnswerUseCase.java
> +                .toList();
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-11-29 05:03 UTC, merged