[FEATURE] 상품 SmallCategory 별로 필터 조회 API 작성
Team-TIFY/TIFY-SERVER pull request #87
Opened 2023-11-05 09:31 UTC by bongsh0112

## 📝 PR Summary

상품 SmallCategory 별로 필터 조회 API 작성

#### 🌲 Working Branch

feat/84-product-list

#### 🌲 TODOs

- [ ] 로직이 맞나 싶음 -> 우선 카테고리별로 상품들 다 가져온다음 list로 addAll()해서 합친 후 slice했는데 이것도 좀..
- [ ] `query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2` 이런 에러가 뜸 ㅠ 미안하다! 쿼리에서 List로 받는데 왜징

### Related Issues

#84

2023-11-05 16:22 UTC, sanbonai06 approved these changes

2023-11-06 00:47 UTC, sanbonai06 requested changes
수정부탁드려용

2023-11-06 00:47 UTC, sanbonai06 commented on Api/src/main/java/tify/server/api/product/service/RetrieveProductListUseCase.java
> +        List<ProductRetrieveDTO> products = new ArrayList<>();
파라미터로 list받는건 프론트 측 요청인가요??

2023-11-06 00:47 UTC, sanbonai06 commented on Domain/src/main/java/tify/server/domain/domains/product/repository/ProductCustomRepositoryImpl.java
> +                                        productCategoryCondition.getCategoryId()))
이 부분을 List<Long> smallCategoryIds로 받아서 
``` java

product.favorQuestionCategoryId.in(smallCategoryIds);
```
로 한번에 처리해서 Slice로 넘기고 서비스레이어에서 별도 처리없이 가는게 더 좋을것 같아요

2023-11-06 00:51 UTC, bongsh0112 commented on Domain/src/main/java/tify/server/domain/domains/product/repository/ProductCustomRepositoryImpl.java
> +                                        productCategoryCondition.getCategoryId()))
헉 in을 생각 못했네요 ㅠㅠ 고맙습니다

2023-11-07 11:19 UTC, sanbonai06 approved these changes

2023-11-07 11:27 UTC, merged